USE impactvizor;

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn, journal_code)
VALUES ('aspb', 'published_articles', '0032-0889', '0032-0889', 'plantphysiol'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn, journal_code)
VALUES ('aspb', 'published_articles', '1532-298X', '1040-4651', 'plantcell'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn)
VALUES ('aspb', 'cohort_articles', '2055-0278', '2055-026X'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn, journal_code)
VALUES ('cshl', 'published_articles', '0890-9369', '0890-9369', 'genesdev'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn, journal_code)
VALUES ('cshl', 'published_articles', '1088-9051', '1088-9051', 'genome'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn)
VALUES ('cshl', 'cohort_articles', '1460-2075', '0261-4189'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn)
VALUES ('cshl', 'cohort_articles', '1097-2765', '1097-2765'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn, journal_code)
VALUES ('besbjs', 'published_articles', '2046-3758', '2046-3758', 'bjres'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn, journal_code)
VALUES ('besbjs', 'published_articles', '2049-4394', '2049-4394', 'jbjsr'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn, journal_code)
VALUES ('besbjs', 'published_articles', '2044-5377', '0301-620X', 'jbjsr'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn)
VALUES ('besbjs', 'cohort_articles', '1535-1386', '0021-9355'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn)
VALUES ('besbjs', 'cohort_articles', '1432-5195', '0341-2695'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn)
VALUES ('besbjs', 'cohort_articles', '1528-1132', '0009-921X'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn, journal_code)
VALUES ('alphamed', 'published_articles', '1549-490X', '1083-7159', 'theoncologist'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn, journal_code)
VALUES ('alphamed', 'published_articles', '2157-6580', '2157-6564', 'sctm'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn)
VALUES ('alphamed', 'cohort_articles', '1527-7755', '0732-183X'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn, journal_code)
VALUES ('portland', 'published_articles', '1470-8736', '0143-5221', 'ppclinsci'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn, journal_code)
VALUES ('portland', 'published_articles', '1470-8728', '0264-6021', 'ppbiochemj'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn)
VALUES ('portland', 'cohort_articles', '1083-351X', '0021-9258'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn, journal_code)
VALUES ('aaas', 'published_articles', '1095-9203', '0036-8075', 'sci'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn, journal_code)
VALUES ('aaas', 'published_articles', '2375-2548', '2375-2548', 'advances'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn, journal_code)
VALUES ('asbmb', 'published_articles', '1083-351X', '0021-9258', 'jbc'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn, journal_code)
VALUES ('asbmb', 'published_articles', '1539-7262', '0022-2275', 'jlr'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn, journal_code)
VALUES ('asbmb', 'published_articles', '1535-9484', '1535-9476', 'mcprot'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn)
VALUES ('asbmb', 'cohort_articles', '1362-4962', '0305-1048'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn, journal_code)
VALUES ('sfn', 'published_articles', '1529-2401', '0270-6474', 'jneuro'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn, journal_code)
VALUES ('sfn', 'published_articles', '2373-2822', '2373-2822', 'eneuro'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn)
VALUES ('sfn', 'cohort_articles', '0896-6273', '0896-6273'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn, journal_code)
VALUES ('blood', 'published_articles', '1528-0020', '0006-4971', 'bloodjournal'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn)
VALUES ('blood', 'cohort_articles', '1476-5551', '0887-6924'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn)
VALUES ('blood', 'cohort_articles', '1592-8721', '0390-6078'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn, journal_code)
VALUES ('aap', 'published_articles', '1098-4275', '0031-4005', 'pediatrics'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn, journal_code)
VALUES ('aap', 'published_articles', '2154-1671', '2154-1663', 'hosppeds'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn)
VALUES ('aap', 'cohort_articles', '2168-6203', '2168-6203'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn, journal_code)
VALUES ('ada', 'published_articles', '0012-1797', '0012-1797', 'diabetes'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn, journal_code)
VALUES ('ada', 'published_articles', '0149-5992', '0149-5992', 'diacare'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn)
VALUES ('ada', 'cohort_articles', '1945-7170', '0013-7227'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn)
VALUES ('ada', 'cohort_articles', '1945-7197', '0021-972X'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn, journal_code)
VALUES ('rup', 'published_articles', '1540-8140', '0021-9525', 'jcb'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn, journal_code)
VALUES ('rup', 'published_articles', '1540-9538', '0022-1007', 'jem'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn, journal_code)
VALUES ('rup', 'published_articles', '1540-7748', '0022-1295', 'jgp'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn)
VALUES ('rup', 'cohort_articles', '1534-5807', '1534-5807'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn)
VALUES ('rup', 'cohort_articles', '1476-4679', '1465-7392'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn, journal_code)
VALUES ('asm', 'published_articles', '1098-5530', '0021-9193', 'jb'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn, journal_code)
VALUES ('asm', 'published_articles', '2150-7511', '2150-7511', 'mbio'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn)
VALUES ('asm', 'cohort_articles', '1931-3128', '1931-3128'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn)
VALUES ('asm', 'cohort_articles', '1751-7370', '1751-7362'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn)
VALUES ('asm', 'cohort_articles', '1553-7374', '1553-7366'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn)
VALUES ('asm', 'cohort_articles', '1365-2958', '0950-382X'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn, journal_code)
VALUES ('pnas', 'published_articles', '1091-6490', '0027-8424', 'pnas'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn)
VALUES ('pnas', 'cohort_articles', '1545-7885', '1544-9173'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn, journal_code)
VALUES ('aan', 'published_articles', '1526-632X', '0028-3878', 'neurology'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn, journal_code)
VALUES ('aan', 'published_articles', '2163-0933', '2163-0402', 'neurclinpract'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn, journal_code)
VALUES ('aan', 'published_articles', '2332-7812', '2332-7812', 'nnn'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn)
VALUES ('aan', 'cohort_articles', '1460-2083', '0964-6906'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn)
VALUES ('aan', 'cohort_articles', '1474-7766', '1474-7758'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn)
VALUES ('aan', 'cohort_articles', '0165-5728', '0165-5728'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn)
VALUES ('rsc', 'published_articles', '2041-6539', '2041-6520'
  );

INSERT INTO impactvizor.publisher_journal (
  publisher_id, product_id, electronic_issn, print_issn)
VALUES ('aspet', 'cohort_articles', '0163-7258', '0163-7258'
  );