from ivetl.pipelines.siteuptime.tasks.get_uptime_stats import GetUptimeStatsTask
from ivetl.pipelines.siteuptime.tasks.insert_stats_into_cassandra import InsertStatsIntoCassandraTask
from ivetl.pipelines.siteuptime.tasks.run_weekly_alerts import RunWeeklyAlertsTask