from cassandra.cqlengine import columns
from cassandra.cqlengine.models import Model
from ivetl import hwcolumns


class HighwireMetadata(Model):
    sort_name = columns.Text()
    site_id = columns.Integer(primary_key=True)
    site_code = columns.Text()
    name = columns.Text()
    site_abbr = columns.Text()
    print_issn = columns.Text()
    online_issn = columns.Text()
    publisher = columns.Text()
    site_url = columns.Text()
    umbrella_code = columns.Text()
    umbrella_url = columns.Text()
    usage_rpts_feature = columns.Text()
    journal_info_feature = columns.Text()
    ac_machine = columns.Text()
    ac_syb_server = columns.Text()
    ac_db = columns.Text()
    ac_port = columns.Text()
    journal_doi = hwcolumns.LowercaseText()
    counter_code = columns.Text()
    dw_syb_server = columns.Text()
    dw_db = columns.Text()
    content_db = columns.Text()
    content_syb_server = columns.Text()
    subman_url = columns.Text()
    legacy_type = columns.Text()
    legacy_date = columns.Text()
    dw_site_type = columns.Text()
    is_book = columns.Text()
    has_athens = columns.Text()
    sage_subject_area = columns.Text()
