from cassandra.cqlengine import columns
from cassandra.cqlengine.models import Model


class Published_Article(Model):
    publisher_id = columns.Text(primary_key=True)
    article_doi = columns.Text(primary_key=True)
    article_issue = columns.Text()
    article_journal = columns.Text()
    article_journal_issn = columns.Text()
    article_pages = columns.Text()
    article_publisher = columns.Text()
    article_scopus_id = columns.Text()
    article_title = columns.Text()
    article_type = columns.Text()
    article_volume = columns.Text()
    citations_lookup_error = columns.Boolean()
    citations_updated_on = columns.DateTime()
    co_authors = columns.Text()
    created = columns.DateTime()
    custom = columns.Text()
    custom_2 = columns.Text()
    custom_3 = columns.Text()
    date_of_publication = columns.DateTime()
    date_of_rejection = columns.DateTime()
    editor = columns.Text()
    first_author = columns.Text()
    from_rejected_manuscript = columns.Boolean()
    has_abstract = columns.Boolean()
    hw_metadata_retrieved = columns.Boolean()
    is_cohort = columns.Boolean()
    is_open_access = columns.Text()
    rejected_manuscript_editor = columns.Text()
    rejected_manuscript_id = columns.Text()
    scopus_citation_count = columns.Integer()
    subject_category = columns.Text()
    month_usage_03 = columns.Integer()
    month_usage_06 = columns.Integer()
    month_usage_09 = columns.Integer()
    month_usage_12 = columns.Integer()
    month_usage_24 = columns.Integer()
    month_usage_36 = columns.Integer()
    usage_start_date = columns.DateTime()
    mendeley_saves = columns.Integer()
    updated = columns.DateTime()
