#!/usr/bin/env bash

IVETL_LOCAL=1
export IVETL_LOCAL

unset IVETL_QA
unset IVETL_PROD

IVETL_ROOT=/iv/impactvizor-pipeline
export IVETL_ROOT

IVETL_CASSANDRA_IP=10.0.1.59
export IVETL_CASSANDRA_IP

DJANGO_SETTINGS_MODULE=ivweb.settings.local
export DJANGO_SETTINGS_MODULE

IVETL_RABBITMQ_BROKER_IP=10.0.1.99
export IVETL_RABBITMQ_BROKER_IP

IVFTP_PUBLIC_IP=52.25.65.132
export IVFTP_PUBLIC_IP
