#!/usr/bin/env bash

IVETL_QA=1
export IVETL_QA

unset IVETL_LOCAL
unset IVETL_PROD

IVETL_ROOT=/iv/impactvizor-pipeline
export IVETL_ROOT

IVETL_CASSANDRA_IP=10.0.0.21
export IVETL_CASSANDRA_IP

DJANGO_SETTINGS_MODULE=ivweb.settings.qa
export DJANGO_SETTINGS_MODULE

IVETL_RABBITMQ_BROKER_URL="amqp://guest:guest@10.0.0.185:5672//"
export IVETL_RABBITMQ_BROKER_URL

#IVFTP_PUBLIC_IP=35.160.219.80
IVFTP_PUBLIC_IP=10.0.0.193
export IVFTP_PUBLIC_IP
