#!/usr/bin/env bash

IVETL_QA=1
export IVETL_QA

unset IVETL_LOCAL
unset IVETL_PROD

IVETL_ROOT=/iv/impactvizor-pipeline
export IVETL_ROOT

IVETL_CASSANDRA_IP=10.0.0.21
export IVETL_CASSANDRA_IP

IVETL_EMAIL_TO_ADDRESS=john@hyperplane.io
export IVETL_EMAIL_TO_ADDRESS

IVETL_TABLEAU_SERVER=10.0.0.143
export IVETL_TABLEAU_SERVER

IVETL_TABLEAU_USERNAME=admin
export IVETL_TABLEAU_USERNAME

IVETL_TABLEAU_PASSWORD=admin
export IVETL_TABLEAU_PASSWORD

IVETL_WEB_ADDRESS=http://10.0.0.232
export IVETL_WEB_ADDRESS

DJANGO_SETTINGS_MODULE=ivweb.settings.qa
export DJANGO_SETTINGS_MODULE

IVETL_RABBITMQ_BROKER_IP=10.0.0.185
export IVETL_RABBITMQ_BROKER_IP
