from ivetl.pipelines.customarticledata.tasks.get_article_data_files import GetArticleDataFiles
from ivetl.pipelines.customarticledata.tasks.validate_article_data_files import ValidateArticleDataFiles
from ivetl.pipelines.customarticledata.tasks.validate_benchpress_article_data_files import ValidateBenchPressArticleDataFiles
from ivetl.pipelines.customarticledata.tasks.insert_custom_article_data_into_cassandra import InsertCustomArticleDataIntoCassandra
