__author__ = 'john'

from ivetl.pipelines.customarticledata.tasks.ValidateArticleDataFile import ValidateArticleDataFile
from ivetl.pipelines.customarticledata.tasks.InsertCustomArticleDataIntoCassandra import InsertCustomArticleDataIntoCassandra