from ivetl.pipelines.sitemetadata.tasks.LoadH20Metadata import LoadH20MetadataTask
from ivetl.pipelines.sitemetadata.tasks.LoadDrupalMetadata import LoadDrupalMetadataTask
from ivetl.pipelines.sitemetadata.tasks.GetChecks import GetChecksTask
from ivetl.pipelines.sitemetadata.tasks.ClassifyChecks import ClassifyChecksTask
from ivetl.pipelines.sitemetadata.tasks.InsertIntoCassandra import InsertIntoCassandraTask
