from ivetl.pipelines.sitemetadata.tasks.LoadMetadataFromFile import LoadMetadataFromFile
from ivetl.pipelines.sitemetadata.tasks.GetChecks import GetChecks
from ivetl.pipelines.sitemetadata.tasks.ClassifyChecks import ClassifyChecks
from ivetl.pipelines.sitemetadata.tasks.InsertIntoCassandra import InsertIntoCassandra