#!/bin/bash

# chkconfig: - 95 05
# description: Enable impactvizor sftp service

. /etc/init.d/functions
. /iv/env/bin/activate
. /iv/impactvizor-pipeline/conf/sftp_prod.sh

name=$(basename "$0");
user="ivftp"
pid_file="/var/run/$name.pid"
dir="/iv/impactvizor-pipeline/ivsftp"
cmd=("python" "sftp.py" "-nofork")

if [ "${IVSFTP_ADDR}" != "" ]; then
	cmd+=("-addr" "${IVSFTP_ADDR}")
fi
if [ "${IVSFTP_PORT}" != "" ]; then
	cmd+=("-port" "${IVSFTP_PORT}")
fi
if [ "${IVSFTP_LOG_LEVEL}" != "" ]; then
	cmd+=("-log-level" "${IVSFTP_LOG_LEVEL}")
fi
for key in dsa ecdsa ed25519 rsa; do
	key_path=/etc/ssh/sftp/sftp_host_${key}_key
	if [ -f "${key_path}" ] && [ -r "${key_path}" ]; then
		cmd+=("-${key}-key" "${key_path}")
	fi
done

get_pid() {
    cat "$pid_file"
}

is_running() {
    [ -f "$pid_file" ] && ps "$(get_pid)" >/dev/null 2>&1
}

case "$1" in
    start)
    if is_running; then
        echo "Already started"
    else
        echo "Starting $name"
        cd "$dir" || exit 1;
        runuser -u "${user}" -- "${cmd[@]}" >"/iv/log/${name}/${name}.out" 2>&1 & echo $! > "$pid_file";
        if ! is_running; then
            echo "Unable to start, check /iv/log/${name}/${name}.out and /iv/log/${name}/${name}.log for errors"
            exit 1
        fi
    fi
    ;;
    stop)
    if is_running; then
        echo -n "Stopping $name.."
        kill "$(get_pid)";
        for i in {1..10}
        do
            if ! is_running; then
                break
            fi

            echo -n "."
            sleep 1
        done
        echo

        if is_running; then
            echo "Not stopped; may still be shutting down or shutdown may have failed"
            exit 1
        else
            echo "Stopped"
            if [ -f "$pid_file" ]; then
                rm "$pid_file"
            fi
        fi
    else
        echo "Not running"
    fi
    ;;
    restart)
    $0 stop
    if is_running; then
        echo "Unable to stop, will not attempt to start"
        exit 1
    fi
    $0 start
    ;;
    status)
    if is_running; then
        echo "Running"
    else
        echo "Stopped"
        exit 1
    fi
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
