from ivetl.pipelines.institutionusage.tasks.get_jr1_files import GetJR1Files
from ivetl.pipelines.institutionusage.tasks.get_jr2_files import GetJR2Files
from ivetl.pipelines.institutionusage.tasks.validate_jr1_files import ValidateJR1Files
from ivetl.pipelines.institutionusage.tasks.validate_jr2_files import ValidateJR2Files
from ivetl.pipelines.institutionusage.tasks.insert_jr1_into_cassandra import InsertJR1IntoCassandra
from ivetl.pipelines.institutionusage.tasks.insert_jr2_into_cassandra import InsertJR2IntoCassandra
