from ivetl.pipelines.institutionusage.tasks.get_jr3_files import GetJR3FilesTask
from ivetl.pipelines.institutionusage.tasks.get_jr2_files import GetJR2FilesTask
from ivetl.pipelines.institutionusage.tasks.validate_jr3_files import ValidateJR3FilesTask
from ivetl.pipelines.institutionusage.tasks.validate_jr2_files import ValidateJR2FilesTask
from ivetl.pipelines.institutionusage.tasks.insert_jr3_into_cassandra import InsertJR3IntoCassandraTask
from ivetl.pipelines.institutionusage.tasks.insert_jr2_into_cassandra import InsertJR2IntoCassandraTask
