USE impactvizor;

INSERT INTO impactvizor.publisher_metadata (publisher_id, hw_addl_metadata_available, issn_to_hw_journal_code, published_articles_issns_to_lookup, published_articles_last_updated, scopus_api_keys)
  VALUES ('blood', true, {'1528-0020':'bloodjournal', '0006-4971':'bloodjournal'}, ['1528-0020'], '2010-01-01 00:00:00', ['654944b76e7d0b335f11a187a6703d24', '3d6949e4df01d95777df49e03e6f81e0']);

INSERT INTO impactvizor.publisher_metadata (publisher_id, hw_addl_metadata_available, issn_to_hw_journal_code, published_articles_issns_to_lookup, published_articles_last_updated, scopus_api_keys)
  VALUES ('aaas', true, {'0036-8075':'sci', '1095-9203':'sci', '2375-2548':'advances'}, ['0036-8075', '2375-2548'], '2010-01-01 00:00:00', ['b7039396d9f1bc737cbc52a9175aa167', 'f2f37c513ae1cb4d36d58891792de09e', '594c9f85140e27dbdbf844756bddef67', '6d6164ec1458fa41d797218b2daa7521']);

INSERT INTO impactvizor.publisher_metadata (publisher_id, hw_addl_metadata_available, issn_to_hw_journal_code, published_articles_issns_to_lookup, published_articles_last_updated, scopus_api_keys)
  VALUES ('pnas', true, {'1091-6490':'pnas', '0027-8424':'pnas'}, ['1091-6490'], '2010-01-01 00:00:00', ['dd404f011c7f5f556ead9f8e83d532a7', '1ac9c575188f653835d9fe18532f434d', '4714d550721b7fe0f21f31c6d61b36bd', '5123f9276addd3c60adb6a0962657d4c']);

INSERT INTO impactvizor.publisher_metadata (publisher_id, hw_addl_metadata_available, issn_to_hw_journal_code, published_articles_issns_to_lookup, published_articles_last_updated, scopus_api_keys)
  VALUES ('rup', true, {'0021-9525':'jcb', '1540-8140':'jcb', '0022-1007':'jem', '1540-9538':'jem', '0022-1295':'jgp', '1540-7748':'jgp'}, ['0021-9525', '0022-1007', '0022-1295'], '2010-01-01 00:00:00', ['a1a9a253d7ca5a4bf4d38e3ac0d211ad', '6d122794a1f086dbec46368829bee0c9']);

INSERT INTO impactvizor.publisher_metadata (publisher_id, hw_addl_metadata_available, issn_to_hw_journal_code, published_articles_issns_to_lookup, published_articles_last_updated, scopus_api_keys)
  VALUES ('aan', true, {'0028-3878':'neurology', '1526-632X':'neurology', '2163-0402':'neurclinpract', '2163-0933':'neurclinpract', '2332-7812':'nnn'}, ['0028-3878', '2163-0402', '2332-7812'], '2010-01-01 00:00:00', ['db07abbc8f1770ba09387cf2ea5bf3fa', 'e40619fb45a51ddf36334f928623f171']);

INSERT INTO impactvizor.publisher_metadata (publisher_id, hw_addl_metadata_available, issn_to_hw_journal_code, published_articles_issns_to_lookup, published_articles_last_updated, scopus_api_keys)
  VALUES ('asbmb', true, {'0021-9258':'jbc', '1083-351X':'jbc', '0022-2275':'jlr', '1539-7262':'jlr', '1535-9476':'mcprot', '1535-9484':'mcprot'}, ['0021-9258', '0022-2275', '1535-9476'], '2010-01-01 00:00:00', ['ea644670597406ffb98d1678a0083640', '35b4fae6b56419f992b3da3379d9b2c0', 'bf0b25b42fe41668b284b77139c0a61c', 'cf524832bc343e5703ea9e43619689da']);

INSERT INTO impactvizor.publisher_metadata (publisher_id, hw_addl_metadata_available, issn_to_hw_journal_code, published_articles_issns_to_lookup, published_articles_last_updated, scopus_api_keys)
  VALUES ('aap', true, {'0031-4005':'pediatrics', '1098-4275':'pediatrics'}, ['0031-4005'], '2010-01-01 00:00:00', ['599526c0bd015ce3ccbbb32abb920aee', 'ae55af99388b449ca3f329ffa97c897a']);

INSERT INTO impactvizor.publisher_metadata (publisher_id, hw_addl_metadata_available, issn_to_hw_journal_code, published_articles_issns_to_lookup, published_articles_last_updated, scopus_api_keys)
  VALUES ('aspb', true, {'1040-4651':'plantcell', '1532-298X':'plantcell', '0032-0889':'plantphysiol', '1532-2548':'plantphysiol'}, ['1040-4651', '0032-0889'], '2010-01-01 00:00:00', ['5831dfc0d00ebf8351f4c9c7af646931', '1aedbeb9264e1a3522513be3d4f115d2']);

INSERT INTO impactvizor.publisher_metadata (publisher_id, hw_addl_metadata_available, issn_to_hw_journal_code, published_articles_issns_to_lookup, published_articles_last_updated, scopus_api_keys)
  VALUES ('cshl', true, {'1088-9051':'genome', '1549-5469':'genome', '0890-9369':'genesdev', '1549-5477':'genesdev'}, ['1088-9051', '0890-9369'], '2010-01-01 00:00:00', ['f2f42a914f28126654cfef9519ebe400']);

INSERT INTO impactvizor.publisher_metadata (publisher_id, hw_addl_metadata_available, issn_to_hw_journal_code, published_articles_issns_to_lookup, published_articles_last_updated, scopus_api_keys)
  VALUES ('besbjs', true, {'2049-4394':'jbjsbr', '2049-4408':'jbjsbr'}, ['2049-4394'], '2010-01-01 00:00:00', ['86fca68e01a0c4ea164643baedd5eebc']);

INSERT INTO impactvizor.publisher_metadata (publisher_id, hw_addl_metadata_available, issn_to_hw_journal_code, published_articles_issns_to_lookup, published_articles_last_updated, scopus_api_keys)
  VALUES ('sfn', true, {'0270-6474':'jneuro', '1529-2401':'jneuro', '2373-2822':'eneuro'}, ['0270-6474', '2373-2822'], '2010-01-01 00:00:00', ['2776603f1c0685a8e96c6015085cc37c', 'ba7c1fd88a74bac505303eb2928d6ac5', '58a897c18145eb98fef6cec605adca73']);

INSERT INTO impactvizor.publisher_metadata (publisher_id, hw_addl_metadata_available, issn_to_hw_journal_code, published_articles_issns_to_lookup, published_articles_last_updated, scopus_api_keys)
  VALUES ('ada', true, {'0012-1797':'diabetes', '1939-327X':'diabetes', '0149-5992':'diacare', '1935-5548':'diacare'}, ['0012-1797', '0149-5992'], '2010-01-01 00:00:00', ['88708df6812fb809c8f50b54b7d1d26f', '97afc65d9a940183912aff0ff1b65faa']);

INSERT INTO impactvizor.publisher_metadata (publisher_id, hw_addl_metadata_available, issn_to_hw_journal_code, published_articles_issns_to_lookup, published_articles_last_updated, scopus_api_keys)
  VALUES ('asm', true, {'0021-9193':'jb', '1098-5530':'jb', '2150-7511':'mbio'}, ['0021-9193', '2150-7511'], '2010-01-01 00:00:00', ['e0afbdd9f0e0fb9b1b477e32d03208ee', 'cb7ddbfee22ce4951316c1b6a474fea1']);

INSERT INTO impactvizor.publisher_metadata (publisher_id, hw_addl_metadata_available, issn_to_hw_journal_code, published_articles_issns_to_lookup, published_articles_last_updated, scopus_api_keys)
  VALUES ('alphamed', true, {'1083-7159':'theoncologist', '1549-490X':'theoncologist', '2157-6564':'sctm', '2157-6580':'sctm'}, ['1083-7159', '2157-6564'], '2010-01-01 00:00:00', ['62588fe8e6f948e95122545208400c19']);

INSERT INTO impactvizor.publisher_metadata (publisher_id, hw_addl_metadata_available, issn_to_hw_journal_code, published_articles_issns_to_lookup, published_articles_last_updated, scopus_api_keys)
  VALUES ('portland', true, {'0264-6021':'ppbiochemj', '11470-8728':'ppbiochemj', '0143-5221':'ppclinsci', '1470-8736':'ppclinsci'}, ['0264-6021', '1470-8736'], '2010-01-01 00:00:00', ['22c5991e02943d30acf4aa83de67f304']);


## For Testing
INSERT INTO impactvizor.publisher_metadata (publisher_id, hw_addl_metadata_available, issn_to_hw_journal_code, published_articles_issns_to_lookup, published_articles_last_updated, scopus_api_keys)
  VALUES ('test', true, {'1528-0020':'bloodjournal', '0006-4971':'bloodjournal'}, ['1528-0020'], '2010-01-01 00:00:00', ['f5bb1dbcd2f625d729836dfcaf5eb5f1', 'f5bb1dbcd2f625d729836dfcaf5eb5f1']);


INSERT INTO impactvizor.publisher_metadata (publisher_id, hw_addl_metadata_available, issn_to_hw_journal_code, published_articles_issns_to_lookup, published_articles_last_updated, scopus_api_keys)
  VALUES ('aaas', true, {'0036-8075':'sci', '1095-9203':'sci', '2375-2548':'advances'}, ['0036-8075', '2375-2548'], '2010-01-01 00:00:00', ['1909c7bd8937a0bdc4c7b298b2941284', 'ccdce910ee2248a800d73cb487847c48', '3fed90a3d3e9807cc43179c3cf94a8a8', 'b87d6249c2028249def7c580fb2698be']);

INSERT INTO impactvizor.publisher_metadata (publisher_id, hw_addl_metadata_available, issn_to_hw_journal_code, published_articles_issns_to_lookup, published_articles_last_updated, scopus_api_keys)
  VALUES ('asbmb', true, {'0021-9258':'jbc', '1083-351X':'jbc', '0022-2275':'jlr', '1539-7262':'jlr', '1535-9476':'mcprot', '1535-9484':'mcprot'}, ['0021-9258', '0022-2275', '1535-9476'], '2010-01-01 00:00:00', ['6930be2049863cf37079dd02a5522e3a', '9abbef1491f184b0ecc74492152bd485', '55866e6325c069376f9d8995bd9e084b', 'f14ad622b64dcc01daf62d42dcbd8d6d']);


