USE impactvizor;

INSERT INTO impactvizor.metadata (publisher_id, issn, last_updated_date, status, file_addl_metadata_source, hw_addl_metadata_source, hw_addl_metadata_journalcodes, issn_to_hw_journal_code)
  VALUES ('blood', '1528-0020', '2010-01-01 17:31:50', false, false, true, '/bloodjournal', {'1528-0020':'bloodjournal', '0006-4971':'bloodjournal'});

INSERT INTO impactvizor.metadata (publisher_id, issn, last_updated_date, status, file_addl_metadata_source, hw_addl_metadata_source, hw_addl_metadata_journalcodes, issn_to_hw_journal_code)
  VALUES ('aan', '0028-3878', '2010-01-01 17:31:50', false, false, true, '/neurology', {'0028-3878':'neurology', '1526-632X':'neurology'});

