from ivetl.pipelines.institutionusage.jr3_institution_usage_pipeline import JR3InstitutionUsagePipeline
from ivetl.pipelines.institutionusage.jr2_institution_usage_pipeline import JR2InstitutionUsagePipeline
